/**
 * Thin desktop-side wrapper over the shared `core` engine.
 *
 * The ENTIRE conversion runs here, in the webview — there is no Rust/Node
 * backend doing the work. This is the same `convert()` the CLI, web server and
 * Cloudflare worker call; the desktop app is just a 4th front-end over `core`.
 * (ExcelJS + core's `Buffer`/`zlib` use is satisfied by the Vite node-polyfill;
 * see vite.config.ts.)
 */
import { convert as coreConvert } from '../../core/src/core/pipeline.js';
import { getFormat, listFormats } from '../../core/src/formats/index.js';
import { compareOutputs } from '../../core/src/output/comparator.js';
import { writeIssuesWorkbook } from '../../core/src/output/issues-writer.js';
import type { FileMeta, FormatId } from '../../core/src/core/types.js';
import type { ConvertResult, ValidationReport } from '../../core/src/core/result.js';
import type { CompareResult } from '../../core/src/output/comparator.js';

export { listFormats, getFormat };
export type { FormatId, ConvertResult, CompareResult };

/** Build the indexed .xlsx errors/warnings report for a validation result. */
export async function exportIssues(report: ValidationReport): Promise<Uint8Array> {
  const buf = await writeIssuesWorkbook(report);
  return new Uint8Array(buf);
}

export interface ConvertInput {
  formatId: FormatId;
  /** Raw .xlsx bytes (from a native file/folder pick or a browser File). */
  bytes: ArrayBuffer;
  memberId: string;
  memberName?: string;
  /** DDMMYYYY, already normalised from the DD/MM/YYYY the user typed. */
  reportingDate?: string;
  creationDate?: string;
  password?: string;
  report?: boolean;
  allowWarnings?: boolean;
}

/** DDMMYYYY -> Date (UTC midnight). Empty/short -> today, matching the web/CLI. */
function parseDate(s?: string): Date {
  if (!s || s.length < 8) return new Date();
  return new Date(Date.UTC(+s.slice(4, 8), +s.slice(2, 4) - 1, +s.slice(0, 2)));
}

export async function runConvert(input: ConvertInput): Promise<ConvertResult> {
  const format = getFormat(input.formatId);
  const meta: FileMeta = {
    memberId: input.memberId,
    memberName: input.memberName,
    reportingDate: parseDate(input.reportingDate),
    creationDate: parseDate(input.creationDate),
    password: input.password,
  };
  return coreConvert(input.bytes, format, meta, {
    allowWarnings: input.allowWarnings,
    report: input.report,
  });
}

export interface ValidateInput extends ConvertInput {
  /** Raw bytes of the existing output / reference file to compare against. */
  referenceBytes: ArrayBuffer;
  /** Compare on content only, ignoring CRLF/LF differences. Default false. */
  ignoreLineEndings?: boolean;
}

export interface ValidateResult {
  /** The conversion result for the input workbook (report, generated bytes). */
  convert: ConvertResult;
  /**
   * The byte comparison of the freshly-generated output vs the supplied
   * reference — present only when the input converted to an output (i.e. it had
   * no blocking errors). When the input itself failed validation, there is
   * nothing to compare, so this is undefined and the convert report explains why.
   */
  compare?: CompareResult;
}

/**
 * Validator: re-convert the input workbook through the same engine and diff the
 * freshly-generated bytes against the user-supplied output/reference file. This
 * is what proves the software's accuracy — if the input is genuine source data
 * for that reference, a clean byte-exact match confirms the engine reproduces the
 * portal-accepted file exactly. Allowing warnings here so a file is still
 * produced to compare even when the input has non-blocking warnings.
 */
export async function runValidate(input: ValidateInput): Promise<ValidateResult> {
  const convert = await runConvert({ ...input, allowWarnings: true, report: false });
  if (!convert.output) {
    // Input had blocking errors → no generated bytes to compare.
    return { convert };
  }
  const compare = compareOutputs(convert.output, input.referenceBytes, {
    ignoreLineEndings: input.ignoreLineEndings,
  });
  return { convert, compare };
}
