import os
import sys
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether, HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas

class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super(NumberedCanvas, self).__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super(NumberedCanvas, self).showPage()
        super(NumberedCanvas, self).save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))
        
        # Header
        self.drawString(36, 760, "CRIF HIGH MARK COMMERCIAL BUREAU AUDIT REPORT")
        self.drawRightString(576, 760, "BATCH: NBF0000708 | 16-AUG-2026 (W2)")
        self.setStrokeColor(colors.HexColor("#CBD5E1"))
        self.setLineWidth(0.75)
        self.line(36, 752, 576, 752)
        
        # Footer
        self.line(36, 45, 576, 45)
        self.drawString(36, 32, "Confidential — Generated by CIC Bureau Submission Diagnostic Engine")
        self.drawRightString(576, 32, f"Page {self._pageNumber} of {page_count}")
        self.restoreState()

def build_pdf(filename):
    doc = SimpleDocTemplate(
        filename,
        pagesize=letter,
        leftMargin=36,
        rightMargin=36,
        topMargin=54,
        bottomMargin=54
    )
    
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=18,
        leading=22,
        textColor=colors.HexColor('#0F172A'),
        spaceAfter=4
    )
    
    subtitle_style = ParagraphStyle(
        'DocSubTitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#475569'),
        spaceAfter=12
    )

    h2_style = ParagraphStyle(
        'H2',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=16,
        textColor=colors.HexColor('#1E293B'),
        spaceBefore=10,
        spaceAfter=6
    )

    body_style = ParagraphStyle(
        'Body',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8.5,
        leading=12,
        textColor=colors.HexColor('#334155')
    )

    table_header_style = ParagraphStyle(
        'TH',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8,
        leading=10,
        textColor=colors.white
    )

    table_cell_style = ParagraphStyle(
        'TC',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=7.5,
        leading=10,
        textColor=colors.HexColor('#1E293B')
    )

    code_cell_style = ParagraphStyle(
        'CodeCell',
        parent=styles['Normal'],
        fontName='Courier-Bold',
        fontSize=7.5,
        leading=9,
        textColor=colors.HexColor('#B91C1C')
    )

    story = []
    
    # Title
    story.append(Paragraph("CRIF Commercial Bureau Rejection Audit & Fix Report", title_style))
    story.append(Paragraph("<b>File Audited:</b> NBF0000708_Commercial_16082026_20082026_144816_W2.txt &nbsp;|&nbsp; <b>Master Sheet:</b> CIC Commercial Data Master Sheet16th August, 2026.xlsx", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#0284C7"), spaceAfter=10))

    # Section 1: Executive Summary
    story.append(Paragraph("1. Executive Summary & Root Cause Analysis", h2_style))
    summary_text = (
        "The submission file was rejected by CRIF High Mark Commercial Bureau Portal due to a combination of "
        "<b>wire-format segment delimiter mismatch (V3.9 vs V3.10)</b> and <b>semantic data discrepancies</b> in the accountant's Master Sheet. "
        "The bureau gateway validates weekly submissions (<code>W2</code>) against the <b>Commercial UCRF V3.10</b> specification. "
        "The table below summarizes the fatal rejection triggers and required corrections."
    )
    story.append(Paragraph(summary_text, body_style))
    story.append(Spacer(1, 8))

    # Summary Table
    summary_data = [
        [Paragraph("Category", table_header_style), Paragraph("Error / Rejection Reason", table_header_style), Paragraph("Bureau Impact", table_header_style), Paragraph("Required Fix", table_header_style)],
        [
            Paragraph("<b>Structural (Wire Spec)</b>", table_cell_style),
            Paragraph("<b>CR Segment Delimiter Count Mismatch</b><br/>Submitted file had 43 pipes (44 fields) instead of 44 pipes (45 fields).", table_cell_style),
            Paragraph("<font color='#DC2626'><b>FATAL</b></font><br/>Gateway parser rejection: invalid field count for V3.10.", table_cell_style),
            Paragraph("Generate using <b>Commercial UCRF V3.10</b> format profile in CIC Export tool (emits 44 pipes).", table_cell_style)
        ],
        [
            Paragraph("<b>Entity Identification</b>", table_cell_style),
            Paragraph("<b>Dummy DUNS '999999999' Emitted</b><br/>DUNS fields in AS, RS, and GS were populated with dummy '999999999'.", table_cell_style),
            Paragraph("<font color='#DC2626'><b>FATAL / ERROR</b></font><br/>CRIF rejects fake/invalid D&B organization numbers.", table_cell_style),
            Paragraph("Leave DUNS fields blank (<code>||</code>) when entity has no real D&B DUNS number.", table_cell_style)
        ],
        [
            Paragraph("<b>Relationship Semantics</b>", table_cell_style),
            Paragraph("<b>Relationship Code Mismatch (Col Z)</b><br/>Accountant entered '12'. In CRIF catalogue, 12 = 'Subsidiary Company', but related person is an individual director.", table_cell_style),
            Paragraph("<font color='#D97706'><b>DATA REJECTION</b></font><br/>Entity type conflict (Individual person cannot be a Subsidiary Company).", table_cell_style),
            Paragraph("Use CRIF Code <b>56</b> for 'Other Director' or <b>51</b> for 'Promoter Director'.", table_cell_style)
        ],
        [
            Paragraph("<b>Director / Guarantor Data</b>", table_cell_style),
            Paragraph("<b>Conflicting DOB for Same PAN</b><br/>Row 4 (Ramesh Datla, PAN AANPD9781G) has DOB 28/09/2002 in RS and 25/10/1961 in GS.", table_cell_style),
            Paragraph("<font color='#DC2626'><b>FATAL ENTITY MISMATCH</b></font><br/>Bureau rejects conflicting demographic profiles for same PAN.", table_cell_style),
            Paragraph("Harmonize Date of Birth in Column AC and Column AQ to actual birth date (25/10/1961).", table_cell_style)
        ],
        [
            Paragraph("<b>Geographic / State Codes</b>", table_cell_style),
            Paragraph("<b>State Code Mismatch (RS Segment)</b><br/>Hyderabad PIN 500045/500033 listed as 'Andhra Pradesh' (Code 02) instead of Telangana (Code 36).", table_cell_style),
            Paragraph("<font color='#D97706'><b>WARNING / AUDIT</b></font><br/>PIN-to-State geographic validation failure.", table_cell_style),
            Paragraph("Update address text to Telangana or specify State Code 36.", table_cell_style)
        ]
    ]

    summary_table = Table(summary_data, colWidths=[90, 180, 110, 160])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0F172A')),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.HexColor('#F8FAFC'), colors.white]),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 14))

    # Section 2: Detailed Technical Findings
    story.append(Paragraph("2. Technical Breakdown: CR Delimiter Count & DUNS Rules", h2_style))
    tech_text = (
        "<b>A. The CR Segment Delimiter Rule (V3.10 Standard):</b><br/>"
        "Under CRIF High Mark Commercial UCRF V3.10 (§7.5), the Credit Facility (<code>CR</code>) segment consists of exactly <b>45 fields (44 pipe delimiters)</b>. "
        "The legacy V3.9 layout had 44 fields (43 pipes) terminating at <code>ufceAmount</code>. V3.10 adds Field 45 (<code>ufceDate</code>). "
        "When the file header contains cycle code <code>W2</code>, the bureau requires full V3.10 field alignment:<br/>"
        "<font color='#0284C7'><b>Rejected CR (43 pipes):</b></font> <code>CR|1983201000162|...|01|||||||||0||00|||||||</code><br/>"
        "<font color='#16A34A'><b>Compliant CR (44 pipes):</b></font> <code>CR|1983201000162|...|01|||||||||0||00||||||||</code><br/><br/>"
        "<b>B. DUNS Number Specification:</b><br/>"
        "DUNS numbers are 9-digit identifiers issued exclusively by Dun & Bradstreet. In previous manual exports, dummy <code>999999999</code> values were inserted into AS Field 3, RS Field 2, and GS Field 2. "
        "Per CRIF specifications, if an entity has no official D&B DUNS, the field must remain completely empty (<code>||</code>)."
    )
    story.append(Paragraph(tech_text, body_style))
    story.append(Spacer(1, 10))

    # Page Break for Accountant Action Items
    story.append(PageBreak())

    # Section 3: Row-by-Row Accountant Action Plan
    story.append(Paragraph("3. Master Sheet Row-by-Row Action Plan for Accountant", h2_style))
    story.append(Paragraph("The accountant should make the following specific corrections in <b>CIC Commercial Data Master Sheet16th August, 2026.xlsx</b> before generating the final submission file:", body_style))
    story.append(Spacer(1, 8))

    row_data = [
        [Paragraph("Row #", table_header_style), Paragraph("Borrower / Account", table_header_style), Paragraph("Column / Field", table_header_style), Paragraph("Current Value", table_header_style), Paragraph("Corrected Value", table_header_style), Paragraph("Reason for Correction", table_header_style)],
        [
            Paragraph("<b>All Rows<br/>(2, 3, 4, 5)</b>", table_cell_style),
            Paragraph("VIRINCHI, VIVO BIO, ELICO, VIRINCHI HEALTH", table_cell_style),
            Paragraph("<b>Col Z</b><br/>(Relationship)", table_cell_style),
            Paragraph("<code>12</code>", code_cell_style),
            Paragraph("<b><code>56</code></b> (or select 'Other Director')", table_cell_style),
            Paragraph("Code 12 = Subsidiary Company. Individual directors must use Code 56 (Other Director) or 51 (Promoter Director).", table_cell_style)
        ],
        [
            Paragraph("<b>Row 4</b>", table_cell_style),
            Paragraph("ELICO LIMITED<br/>(Acct: 10558726624)", table_cell_style),
            Paragraph("<b>Col AC vs Col AQ</b><br/>(Director vs Guarantor DOB)", table_cell_style),
            Paragraph("Col AC: <code>28092002</code><br/>Col AQ: <code>25101961</code>", code_cell_style),
            Paragraph("Both: <b><code>25101961</code></b>", table_cell_style),
            Paragraph("Ramesh Datla (PAN AANPD9781G) is listed with DOB 2002 as Director and 1961 as Guarantor. Conflicting DOB causes fatal bureau entity mismatch.", table_cell_style)
        ],
        [
            Paragraph("<b>Row 2, 4, 5</b>", table_cell_style),
            Paragraph("Maddala Veera Srinivasa Rao & Ramesh Datla", table_cell_style),
            Paragraph("<b>Col AE</b><br/>(Related Person Address)", table_cell_style),
            Paragraph("Text says 'Andhra Pradesh-500045'", code_cell_style),
            Paragraph("Text should say <b>'Telangana - 500045'</b>", table_cell_style),
            Paragraph("Jubilee Hills PIN 500045/500033 is in Telangana (State Code 36). Text discrepancy causes State Code 02 to be parsed.", table_cell_style)
        ],
        [
            Paragraph("<b>Row 2 & 4</b>", table_cell_style),
            Paragraph("VIRINCHI LIMITED & ELICO LIMITED", table_cell_style),
            Paragraph("<b>Col A & Col AR</b><br/>(Company Name / PAN)", table_cell_style),
            Paragraph("Trailing space in name/PAN", code_cell_style),
            Paragraph("<b>Trim spaces</b>", table_cell_style),
            Paragraph("'VIRINCHI LIMITED ' and PAN 'AANPD9781G ' contain trailing spaces. Clean extra whitespace to prevent format shift.", table_cell_style)
        ]
    ]

    row_table = Table(row_data, colWidths=[40, 95, 80, 85, 95, 145])
    row_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0F172A')),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.HexColor('#F8FAFC'), colors.white]),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    story.append(row_table)
    story.append(Spacer(1, 14))

    # Section 4: How to Generate Compliant File
    story.append(Paragraph("4. Step-by-Step Instructions to Generate Valid Submission File", h2_style))
    steps_text = (
        "<b>1. Correct Master Sheet:</b> Update the 4 items listed in the table above in Excel and save the file.<br/>"
        "<b>2. Open CIC Converter App:</b> Launch <code>CIC Converter (Gated)</code> on your computer.<br/>"
        "<b>3. Select Format:</b> In the Format dropdown, ensure <b>'Commercial UCRF V3.10'</b> (default) is selected.<br/>"
        "<b>4. Verify Details:</b> Enter Member ID <code>NBF0000708</code>, select Reporting Cycle <b>W2 (16th Aug)</b>.<br/>"
        "<b>5. Click Generate:</b> Click <b>'Generate submission file'</b> to save the verified <code>.txt</code> file.<br/>"
        "<b>6. Validate Before Upload:</b> You can also switch to the <b>Validator</b> tab and click <i>'Run validation on Master Sheet'</i> to confirm 0 errors before portal submission."
    )
    story.append(Paragraph(steps_text, body_style))

    doc.build(story, canvasmaker=NumberedCanvas)
    print(f"PDF built successfully at: {filename}")

if __name__ == '__main__':
    p1 = '/Users/praffult45/Desktop/Work/crif-export/training-references/commercial-debugging-aug-16/CRIF_Commercial_Data_Correction_Report_NBF0000708.pdf'
    p2 = '/Users/praffult45/Desktop/Work/crif-export/CRIF_Commercial_Data_Correction_Report_NBF0000708.pdf'
    build_pdf(p1)
    build_pdf(p2)
